### ISSUE TITLE
Constrain numerical values

### ISSUE THREAD

**Issue by strayblues** [strayblues/corona#11]
If a variable holds a numerical value, that value should be constrained by an upper and lower bound.
## TODO 
- [ ] In here: list all variables holding numerical values and specify their constraints
- [ ] In code: implement and test

## Constraints
- [ ] Total patients num throughout the game (inc. unconfirmed) ≤ population (guaranteeing num of dead is also ≤ population).
- [ ] Economic state: 0-100
- [ ] National happiness: 0-100
